name: Check useBindings Usage

on:
  pull_request:
    branches: [ main ]

jobs:
  check-bindings:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: 'libs/**/*-root.tsx'
          
      - name: Check for useBindings
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Initialize array for missing useBindings
          missing_bindings=()
          
          # Check each changed -root.tsx file
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking $file for useBindings usage..."
            
            # Check if file contains useBindings or the exemption comment
            if ! grep -q "useBindings" "$file" && ! grep -q "no-bindings" "$file"; then
              missing_bindings+=("$file")
            fi
          done
          
          # Report missing useBindings
          if [ ${#missing_bindings[@]} -gt 0 ]; then
            echo "::error title=Missing useBindings::❌ Root components should use useBindings"
            echo "::group::Components missing useBindings"
            
            for file in "${missing_bindings[@]}"; do
              echo "::error file=$file::Root component is missing useBindings"
            done
            
            echo "::endgroup::"
            
            echo "::group::How to fix"
            echo "useBindings is expected on the root component to make state management easier with the bind syntax."
            echo ""
            echo "Example usage:"
            echo '```tsx'
            echo 'const { valueSig, disabledSig } = useBindings(props, {'
            echo '  value: "",'
            echo '  disabled: false'
            echo '});'
            echo '```'
            echo ""
            echo "If the component does not need to use bindings, add this comment in the file:"
            echo "// no-bindings"
            echo ""
            echo "See documentation: https://qwik.design/contributing/state/#useBindings"
            echo "::endgroup::"
            
            exit 1
          else
            echo "✅ All root components either use useBindings or are properly exempted."
          fi